### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by qiming111** [posenhuang/deeplearningsourceseparation#12]
Excuse me.When I run the demos there are some errors.It reports that there is no stft3 function,and wrongly use horzcat function.The projects is a little big.It will be a little challenging to find the bugs,so I hope that you can give me some advise.Thank you very much.

**Comment by posenhuang** [comment]
I added the stft3 https://github.com/posenhuang/deeplearningsourceseparation/commit/f634d05fd61f0d18b1a232c4179e59f46609ade1  function. Can you give me more details such that I can reproduce the error?

**Comment by qiming111** [comment]
Sorry to reply you too late.I went outsides for a week.Thanks for your help.Now almost all the demos work except TSP model.The error is "There is no file "train.fea" in folder ''codes\TSP\demo\results" for htkread function to read".Do you forget to add train.fea or something else?

**Comment by posenhuang** [comment]
I think you don't have HTK installed. 
https://github.com/posenhuang/deeplearningsourceseparation/blob/81bcc535a52979781a6c8ff53e7bbb3798b7ffda/codes/compute_features.m#L40
It is created by HCopy.
