### ISSUE TITLE
denoising training code

### ISSUE THREAD

**Issue by manhwag** [posenhuang/deeplearningsourceseparation#15]
I wonder if you can upload denoising training code.

**Comment by posenhuang** [comment]
I might be able to pull some messy version. But essentially it should be similar to other experiments except the data.

**Comment by manhwag** [comment]
Thats not problem. I want to use separated trainig data like denoising code. (mir1k training data has voice and music in one file as stereo). So I have modified your mir1k training code for denoising training code. But the performance of the results are not good as your denoising results. I want to compare with your denoising training code.

**Comment by posenhuang** [comment]
I see. I'll work on it recently (needs to be cleaned and tested again). I'll update this thread once it is done.

**Comment by posenhuang** [comment]
FYI: I add the training codes here: https://github.com/posenhuang/deeplearningsourceseparation/pull/18
