### ISSUE TITLE
Would you please share the demo for denoising_model training?

### ISSUE THREAD

**Issue by youngsuenXMLY** [posenhuang/deeplearningsourceseparation#16]
First, what brilliant work you have done! 
I found your denoising demo without model training application. Would you please share a m-file for denoising model training. Your reply will be highly appreciated! Thank you.

**Comment by posenhuang** [comment]
I'll work on it recently :) It's a bit messy now. I'll update the thread once it is done.

**Comment by youngsuenXMLY** [comment]
Hi ,posenhuang
    I mixed 2hours music and speech data at SNR=0 for training, and get satisfactory result. But there is still some problem in internal memory usage. I used a PC with 64GB internal memory, after formulate_data function in formulate_data .m, the internal memory is full, even worse the internal memory swap data with hard disk. I think the main reason is that in formulate_data function, the background music data(variable 'train2') is shift-repeated floor(lenghth(train2)/shift_size ) times, so the
feature data correspondingly increased.
Is there any solution to reduce internal memory usage?

**Comment by posenhuang** [comment]
You can try to adjust the shift size to reduce the memory. Also are you using drnn_mini? It is a mini-batch lbfgs. It should use less memory. FYI: I just pushed the training code here (merged to master): https://github.com/posenhuang/deeplearningsourceseparation/pull/18
