### ISSUE TITLE
TSP

### ISSUE THREAD

**Issue by jackjct** [posenhuang/deeplearningsourceseparation#17]
To run this m file it is necessary some parameters, could you give the ones to run the example
TSP_model_RNN1_win1_h300_l2_r0_64ms_1000000_softabs_linearout_RELU_logmel_trn0_c1e-10_c0.001_bsz100000_miter10_bf50_c0_d0_7650.mat

train_TSP_demo_mini_clip(context_win, hidden_units, num_layers, isdropout, isRNN, iscleanonly,...
    circular_step , isinputL1, MFCCorlogMelorSpectrum, framerate, pos_neg_r, outputnonlinear, opt, act, ...
    train_mode, const, const2, isGPU, batchsize, MaxIter, bfgs_iter, clip, lambda,...
    data_mode)

**Comment by posenhuang** [comment]
See https://github.com/posenhuang/deeplearningsourceseparation/blob/master/codes/TSP/train_TSP_demo_mini_clip.m#L299-L347

**Comment by jackjct** [comment]
Thank you!!
