### ISSUE TITLE
Denoising Demo not working

### ISSUE THREAD

**Issue by Sylvus** [posenhuang/deeplearningsourceseparation#2]
Hi, it seems like the code in the denoising folder is not up to date. First I received an error that the model file was not found so I renamed that file. Then I received an error that the formulate_data_test function is missing. If I add it (from the timit or TSP folder) I get yet another error:

> Error using  - 
> Matrix dimensions must agree.
> 
> Error in test_denoising_general_kl_bss3 (line 56)
>     output.source_noise= spectrum.mix-output.source_signal;

The previous error looked like this:

>  run_test_single_model
> Warning: Name is nonexistent or not a directory: ......\codes\denoising\Data 
>  In path (line 109)
>   In addpath (line 88)
>   In run_test_single_model (line 7) 
> Warning: Name is nonexistent or not a directory: ......\codes\denoising\drnn 
> In path (line 109)
>   In addpath (line 88)
>   In run_test_single_model (line 8) 
> Undefined function or variable 'formulate_data_test'.
> 
> Error in test_denoising_general_kl_bss3 (line 14)
>                                 formulate_data_test(mixture, eI, testmode);
> 
> Error in run_test_single_model (line 38)
>     output = test_denoising_general_kl_bss3(x', theta, eI, 'testall', 0);

I will try to fix it myself but if you have time I would appreciate your help. Thank you.

**Comment by posenhuang** [comment]
Looks like some path issue. Let me check it later today. Thanks for reporting!

**Comment by Sylvus** [comment]
yes I'm still stuck. I can run the other demos though, seems only the denoising does not work. Thanks for looking into it!

**Comment by posenhuang** [comment]
Hi @Sylvus, please check the latest version. I've added the missing files:  https://github.com/posenhuang/deeplearningsourceseparation/pull/3
Let me know if you have any questions.

**Comment by Sylvus** [comment]
Thank you very much. The demo runs and I can also test it on my own sound files. Two more things:

1)
In run_test_single_model you use audiowrite(...,16000) to write the output. I think you should use fs instead of 16000. Otherwise my input files (fs=42000) get messed up. 

2)
Is it possible to train a denoising model in an unsupervised fashion (I don't have any labels)? Should I look at the other demos to find out how? I would like to do that because right now the separation from the 870 model is okay but not really that great...

**Comment by posenhuang** [comment]
1. Thanks. I fixed it: 81bcc535a52979781a6c8ff53e7bbb3798b7ffda 
2. It is still a research topic. In the mismatch condition, the performance is worse in the papers.
