### ISSUE TITLE
minFunc returns 'Step direction is illegal!'

### ISSUE THREAD

**Issue by youngsuenXMLY** [posenhuang/deeplearningsourceseparation#20]
Hi,posenhuang
    I use 3 hours' mandarin speech to train mir1k. The SNR is [-5,0,5,10,15,20]dB and clean data is SNR infinite condition.  The left channel of clean data is filled with all zeros.
    In minFunc.m, line 963-967, a legal number check is implemented and I got the error 'Step direction is illegal!'. I think there must be some data illegal, but I don't know where the problem is. Would you please 
help me to solve this problem?

**Comment by youngsuenXMLY** [comment]
I solved this porblem. The problem is division with zero denominator.
In file formulate_data.m and test_mir1k_general_kl_bss3.m, s1 and s2 should be normalized using 
s1=s1./(sqrt(sum(s1.^2))+eps);
s2=s2./(sqrt(sum(s2.^2))+eps);
to avoid division by zero.

**Comment by posenhuang** [comment]
Thanks! Feel free to submit a pull request.
