### ISSUE TITLE
Training ERROR with "Not enough input arguments."

### ISSUE THREAD

**Issue by b03201003** [posenhuang/deeplearningsourceseparation#21]
Hi, I am a beginner in matlab.
I'm interesting in singing voice separation project,
so I cloned your project and tried to execute "train_mir1k_demo" in matlab. 
However, I got:
Error in train_mir1k_demo (line 58)
eI.MFCCorlogMelorSpectrum=MFCCorlogMelorSpectrum;

I'm wondering how to set the MFCCorlogMelorSpectrum value when executing this code in terminal.
ThankU!!

**Comment by posenhuang** [comment]
Hi thanks for your interests. I think the value will be loaded when you run `train_mir1k_demo.m`. The `MFCCorlogMelorSpectrum` value is here https://github.com/posenhuang/deeplearningsourceseparation/blob/master/codes/mir1k/train_mir1k_demo.m#L324

**Comment by posenhuang** [comment]
Close for now. Feel free to reopen if you encounter problems. Thanks!
