### ISSUE TITLE
After training, where is the model saved?

### ISSUE THREAD

**Issue by qq932546734** [posenhuang/deeplearningsourceseparation#23]
Hi, posenhuang. Thank you for your wonderful work. I have tried to train the denoising demo with timit corpus. It seems like that the training process is successful, which cost me 5h:43m:44.3s. The problem is I can't find the trained model. Could you please tell me where can I find it?

**Comment by qq932546734** [comment]
OK, I have found it. My mistake.

**Comment by qq932546734** [comment]
Hello again! I reopen this issue, hoping you can help me solve some confusion. 

Background: I downloaded your trained model --"denoising_mode_870.mat" and tested it on my own dataset (just some randomly picked audios from production). It showed a great performance on denoising, which I feel really satisfied (thank you for your work). However, my audios are in framerate of 8000Hz. When I test on the original audios without transcoding or resampling it to 16000HZ, denoising does not work. But after transcoding it to 16000Hz, it works well. And during the process, I found the time cost is relatively long as to 40s for a 1:30 mins audio. It only took 10s for the same audio if it is in 8000Hz, although in this case, denoising didn't work. All to all, I came with the idea of retraining the model with TIMIT corpus after transcoding it to 8000Hz. 

Here is the problem that confused me:
1. Does framerate affect time cost for denoising?
2. After training, there are lots of models separated in two directories, in each of which sits 23 models. I am wondering what is the difference between these model. And which one should I choose for the best performance?
3. I tried several of my retrained models, no one can have a good performance concerning denoising compared with the model `denoising_mode_870.mat`.
4. Since I want to accelerate the denoising procedure (testing, not training), I tried to use the GPU version of `drdae_discrim_joint_kl_obj.m` in `test_denoising_general_kl_bss3.m`. But even I tried hard, I can't make it run successfully ( I am not very familiar with MATLAB). Can I using `drdae_discrim_joint_kl_obj_gpu.m` or `drdae_discrim_joint_kl_obj_gpu_relu.m` in testing to accelerate the program? 

Sorry for these verbose questions. Thank you for your time.

**Comment by posenhuang** [comment]
Hello, thanks for your interests. Sorry, I don't have Matlab access now and I haven't used Matlab for a while. For your questions,
1. I think the 8kHz vs 16kHz could be related to training/testing mismatch, as they are quite different in frequency domain.
2. I think those are just models saved in different iterations. 
3. It is hard to justify why and debug. Are you running [this](https://github.com/posenhuang/deeplearningsourceseparation/blob/master/codes/denoising/train_denoising_demo.m)? 
4. I think I used [drdae_discrim_joint_kl_obj_gpu_relu.m ](https://github.com/posenhuang/deeplearningsourceseparation/blob/master/codes/denoising/drnn/train_denoising_mini.m#L112)in the demo code I provided.

**Comment by qq932546734** [comment]
Thank you for your reply and your patience. It helps a lot. It is really hard to draw a conclusion without practice. I would try more. Thank you again.

**Comment by posenhuang** [comment]
Close this issue unless you have other questions.
