### ISSUE TITLE
Are you using the RNN for denoising task?

### ISSUE THREAD

**Issue by Lynlzz1314** [posenhuang/deeplearningsourceseparation#24]
Hi, 
   posenhuang.  Do you use RNN in denoising task?

**Comment by posenhuang** [comment]
yes

**Comment by Lynlzz1314** [comment]
In the test phase,  T represents  the feature data of each frame, and is it processed by frame?

**Comment by posenhuang** [comment]
You mean T in https://github.com/posenhuang/deeplearningsourceseparation/blob/f7bad7c1f037f5b3673fe45e57229a256d579524/codes/denoising/demo/formulate_data_test.m#L57? 
I think it concatenates neighbouring frames and then are processed by frame in RNN.
