### ISSUE TITLE
Timit

### ISSUE THREAD

**Issue by kianakheirkhah** [posenhuang/deeplearningsourceseparation#27]
Hi, I am a beginner in matlab.
I'm interesting in singing voice separation project,
so I cloned your project and tried to execute "train_timit_demo" in matlab.
However, I got:
Error in train_timit_demo (line 58)
eI.MFCCorlogMelorSpectrum=MFCCorlogMelorSpectrum;

I'm wondering how to set the MFCCorlogMelorSpectrum value when executing this code in terminal.
Thank you so much!

I found your answer about the same question for "train_mir1k_demo". Can I use the same values?

**Comment by posenhuang** [comment]
I think MFCCorlogMelorSpectrum=1 or 2 should work. 
I checked the code. It was written in a weird way: I defined the function first and provided the config, execution command in the end. 
Hence, I think the MFCCorlogMelorSpectrum value is provided here: https://github.com/posenhuang/deeplearningsourceseparation/blob/f7bad7c1f037f5b3673fe45e57229a256d579524/codes/timit/train_timit_demo.m#L243.

**Comment by kianakheirkhah** [comment]
Thanks in advance for your help.

I got another error in train_timit_demo:
"Undefined function or variable 'nfeat'." in formulate_data.
so there is an error in train_timit_demo:
"[data_cell, targets_cell, mixture_spectrum]=formulate_data(train1, train2, eI, eI.train_mode)"

I think the problem raised because wavread is used to define train1, train2 and I replaced it by audioread.

Could you please help me to solve this error?

**Comment by posenhuang** [comment]
It could be related to audioread. If possible, can you try it on the MATLAB R2015a? 
Also, you might need to check whether you have HTK installed properly as we are using HTK to compute features there.
Sorry I don't have access to matlab now.

**Comment by kianakheirkhah** [comment]
Thank you for your advice. I tried it in MATLAB R2015a and installed HTK
but the problem is remained. Do you have any suggestion?
When I run train_timit_demo the error is exactly this:

'' Undefined function or variable 'nfeat'.

Error in formulate_data (line 61)
    target_ag{i} = zeros(2*nfeat*eI.seqLen(i),seqLenSizes(i));

Error in train_timit_demo (line 222)
[data_cell, targets_cell, mixture_spectrum]=formulate_data(train1, train2,
eI, eI.train_mode); %0 --
chunk, 2--no chunk ''

**Comment by posenhuang** [comment]
Maybe something is wrong during the data preprocessing. nfeat should be generated in here: https://github.com/posenhuang/deeplearningsourceseparation/blob/f7bad7c1f037f5b3673fe45e57229a256d579524/codes/timit/formulate_data.m#L47
Perhaps it is not going through the loop here: https://github.com/posenhuang/deeplearningsourceseparation/blob/f7bad7c1f037f5b3673fe45e57229a256d579524/codes/timit/formulate_data.m#L34.
Can you run other demos?

**Comment by kianakheirkhah** [comment]
I run other demo. It is train_mir1k_demo.
There is a new error: "dot indexing is not supported for variables of this type."

The error is again because of formulate_data when I put:
seqLen = [50];
eI.seqLen = seqLen

**Comment by PlutoChu** [comment]
The first error you encountered was caused by setting the parameter 'train-mode' to '0'. You can try again by setting this parameter to '1'.
But I also encountered some problems...details is as follows:
'HCopy' 不是内部或外部命令，也不是可运行的程序 
或批处理文件。 
Error using htkread (line 20)
Unable to read from file
..\..\codes\timit\discrim_joint_offset_all_results\model_DNN_win1024_h150_l2_cleanonly_r1_16ms_512_softabs_kl_const_linearout_RELU_L1_mfcc_trn1_c1_c1\train.fea

I want to know how you set the parameters of train_timit_demo, such as 'context_win', 'circular_step', 'framerate', 'pos_neg_r', 'const' and 'const2'. I will be very appreciated if you can give me some advices.

**Comment by posenhuang** [comment]
@PlutoChu, I think you haven't installed HTK properly. For the parameters, you can find them at https://github.com/posenhuang/deeplearningsourceseparation/blob/master/codes/timit/train_timit_demo.m#L228.

**Comment by apprentissagee** [comment]
@posenhuang how can install htk ?

**Comment by posenhuang** [comment]
@apprentissagee It might be tricky to debug htk install as it depends on your environment. I believe there are many tutorial online.

**Comment by rajaa57** [comment]
Hi, I am a beginner in matlab.
my question is how to get the same results in the paper ??
by using the whole timit dataset or just the training female and male voices that posted with the code ?
