### ISSUE TITLE
Training (ERROR) 

### ISSUE THREAD

**Issue by apprentissagee** [posenhuang/deeplearningsourceseparation#28]
HI Excuse me, I am a beginner in programming. I am working on a project of audio source separation , really interested in this code, if you can helpe me ... i have two  problems :
1_ Error en Training code: codes/mir1k/train_mir1k_demo.m 
Undefined function or variable "data_ag".

Error in formulate_data (line 223)
theoutputs = {data_ag, target_ag, mixture_ag};

Error in train_mir1k_demo (line 220)
[data_cell, targets_cell, mixture_spectrum]=formulate_data(train_files, eI, eI.train_mode); %0 -- chunk, 2--no chunk, 3- icassp

Error in tr (line 62)
train_mir1k_demo(context_win, hidden_units, num_layers, isdropout, ...
2_ I have a problem in the installation of htk, i can't install it, does the problem come back from there ? if so, how can i install it provided i downloaded the file ?

**Comment by posenhuang** [comment]
Sorry to get back to this late. It seems that it is related to the data. It might be tricky to debug htk install as it depends on your environment. I believe there are many tutorial online.
