### ISSUE TITLE
could it be used in real time ?

### ISSUE THREAD

**Issue by ucasiggcas** [posenhuang/deeplearningsourceseparation#29]
Dear,
I want to use the method to solve the howling in RTC-Real Time Communication,
so could I separate the noise and voice frame by frame ?

any reference will be appreciated.

thx

**Comment by posenhuang** [comment]
I believe it is possible! I think it might require writing inference code more efficiently and using hardware acceleration.

**Comment by ucasiggcas** [comment]
So I want to know that whether  the input signal length can be modified and which parameter should I change if I need.
thx

**Comment by ucasiggcas** [comment]
maybe you misunderstand the howling, it's very strong in RTC, like the pic down,
![image](https://user-images.githubusercontent.com/35590066/63928946-231adb80-ca83-11e9-92a7-1376e21368c1.png)
the up is howling and the down voice

**Comment by posenhuang** [comment]
I'm not familiar with this application, but it looks doable when looking at the spectrogram. You might need to check "Work on your data" section in the readme.
