### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by faroit** [posenhuang/deeplearningsourceseparation#4]
Hi, we want reference your implementation in a paper and need to know the software license of your work.

what is the license of this software? Maybe you can add a `LICENSE.md` file in your root folder.

**Comment by posenhuang** [comment]
I've added it to readme. Thanks!

**Comment by faroit** [comment]
just a small addition: if you want to prevent commercial usage you can just pick the GPL license and add that a commercial license is available too.

**Comment by posenhuang** [comment]
Sounds good. Thanks!

**Comment by faroit** [comment]
See e.g. https://github.com/Ableton/link for an example:

> Ableton Link is dual licensed under GPLv2+ and a proprietary license. If you would like to incorporate Link into a proprietary software application, please contact link-devs@ableton.com.

sorry for bothering you, but I am currently working on a paper whichs lists implementations of source separation methods and yours were the only ones without a standardised license...

Cheers ;-)

**Comment by posenhuang** [comment]
Thanks! Add Apache License.

**Comment by faroit** [comment]
alright. I will increase your citations then ;-)

**Comment by posenhuang** [comment]
Update this thread. Change license to MIT and add the license in the header: https://github.com/posenhuang/deeplearningsourceseparation/pull/19
