### ISSUE TITLE
tensorflow based implementation

### ISSUE THREAD

**Issue by crosofg** [posenhuang/deeplearningsourceseparation#9]
Does anyone has tensorflow based implementation for this?

**Comment by posenhuang** [comment]
Contribution is welcome. I can provide the link here. It shouldn't be hard to implement in tensorflow.

**Comment by crosofg** [comment]
Can you help me get started? How is the code organised?

**Comment by posenhuang** [comment]
A related read: https://andabi.github.io/music-source-separation/#requirements
